In [251]:
import numpy as np
import matplotlib as plt
import pymysql
from datetime import datetime, timedelta
from sshtunnel import SSHTunnelForwarder
import pandas as pd
% matplotlib inline
import seaborn as sns

## 8/2

In [4]:
# vips 공시 database에서 유가증권, 코스피 공시 데이터만 select >> dataframe으로 return
with SSHTunnelForwarder(
         ('1.212.234.245', 486),
         ssh_password="vips",
         ssh_username="vips",
         remote_bind_address=('127.0.0.1', 3306)) as server:

    conn = pymysql.connect(host='localhost',
                           port=server.local_bind_port,
                           user='root',
                           passwd='qlqtmajrwk',
                           db='dg',
                           charset='utf8')

    curs = conn.cursor(pymysql.cursors.DictCursor)
    
    sql = "select * from dg.searchDB where (crp_cls = 'K' or crp_cls = 'Y')"
    curs.execute(sql)
    rcp_table = curs.fetchall()

server.stop()

In [21]:
with SSHTunnelForwarder(
         ('1.212.234.245', 486),
         ssh_password="vips",
         ssh_username="vips",
         remote_bind_address=('127.0.0.1', 3306)) as server:

    conn = pymysql.connect(host='localhost',
                           port=server.local_bind_port,
                           user='root',
                           passwd='qlqtmajrwk',
                           db='dg',
                           charset='utf8')

    curs = conn.cursor(pymysql.cursors.DictCursor)
    
    sql2 = "select * from dg.stockDB"
    curs.execute(sql2)
    stock_table = curs.fetchall()
    conn.commit()
    conn.close()
    
    
server.stop()

In [5]:
# 0812 13:07 기준 1297983개 공시
len(rcp_table)

1297983

In [203]:
# convert from list of dict  to dataframe
rcp_df = pd.DataFrame.from_dict(rcp_table)

In [204]:
rcp_df['rcp_dt'] = pd.to_datetime(rcp_df['rcp_dt'])
rcp_df['rcp_year'] = rcp_df['rcp_dt'].dt.year
rcp_df['rcp_month'] = rcp_df['rcp_dt'].dt.month
rcp_df['rcp_day'] = rcp_df['rcp_dt'].dt.day

In [205]:
rcp_df['rcp_dayofweek'] = rcp_df['rcp_dt'].dt.dayofweek
# The day of the week with Monday=0, Sunday=6

In [206]:
rcp_df.tail()

,crp_cd,crp_cls,crp_nm,flr_nm,rcp_dt,rcp_no,rcp_rt,rmk,rpt_cat,rpt_nm,rcp_year,rcp_month,rcp_day,rcp_dayofweek
1297978,080420,K,모다이노칩,모다이노칩,2018-08-02,20180802900089,10:05,코,None,연결재무제표기준영업(잠정)실적(공정공시),2018,8,2,3
1297979,072770,K,네오디안테크놀로지,네오디안테크놀로지,2018-08-02,20180802900119,10:45,코,None,주주총회소집결의,2018,8,2,3
1297980,080160,K,모두투어,모두투어,2018-08-02,20180802900120,10:44,코,None,기업설명회(IR)개최,2018,8,2,3
1297981,072770,K,네오디안테크놀로지,네오디안테크놀로지,2018-08-02,20180802900122,10:48,코,None,주식명의개서정지(주주명부폐쇄),2018,8,2,3
1297982,043590,K,크로바하이텍,크로바하이텍,2018-08-02,20180802900130,11:29,코,None,유상증자1차발행가액결정,2018,8,2,3

In [25]:
rcp_df.groupby('rcp_day')['rcp_no'].count()

rcp_day
1     31749
2     41887
3     37127
4     38264
5     35365
6     36216
7     40725
8     43111
9     42213
10    50875
11    38990
12    42138
13    47742
14    68622
15    53263
16    46661
17    35189
18    34623
19    33849
20    36395
21    36344
22    37300
23    37213
24    37979
25    37535
26    40323
27    45300
28    48797
29    48078
30    54580
31    39517
Name: rcp_no, dtype: int64

In [15]:
rcp_df.groupby('rcp_dayofweek')['rcp_no'].count()

rcp_dayofweek
0    242979
1    236425
2    224200
3    256788
4    318061
5     19530
Name: rcp_no, dtype: int64

In [16]:
rcp_df.groupby('rcp_year')['rcp_no'].count()

rcp_year
1999      1102
2000     20387
2001     32075
2002     45489
2003     61364
2004     63287
2005     64288
2006     61674
2007     68520
2008     70355
2009     79657
2010     74374
2011     77785
2012     75321
2013     80175
2014     84694
2015     91806
2016     92725
2017    100678
2018     52227
Name: rcp_no, dtype: int64

## rcp_dt를 언제부터 쌓고 있는지 확인

In [20]:
rcp_df[lambda x : x.rcp_year == 2007] #68520

,crp_cd,crp_cls,crp_nm,flr_nm,rcp_dt,rcp_no,rcp_rt,rmk,rpt_cat,rpt_nm,rcp_year,rcp_month,rcp_day,rcp_dayofweek
335053,011780,Y,금호석유화학,금호석유화학,2007-06-05,20060918800050,None,유,ET_01,기타경영사항(자율공시),2007,6,5,1
345297,034120,Y,SBS,SBS,2007-02-09,20061201800222,None,유,None,주주총회소집결의,2007,2,9,4
345811,000680,Y,LS네트웍스,LS네트웍스,2007-01-09,20061206800176,None,유,G_02,최대주주등소유주식변동신고서(최대주주변경시),2007,1,9,1
346428,008040,Y,사조동아원,사조동아원,2007-01-09,20061211800103,None,유,G_02,최대주주등소유주식변동신고서(최대주주변경시),2007,1,9,1
346656,002380,Y,케이씨씨,케이씨씨,2007-01-08,20061212800243,None,유,E_4,결산실적공시예고(안내공시),2007,1,8,0
346869,005930,Y,삼성전자,삼성전자,2007-01-15,20061213800072,None,유,G_01,최대주주등소유주식변동신고서,2007,1,15,0
347190,003570,Y,S&T중공업,S&T중공업,2007-03-13,20061214800331,None,유,B_7,단일판매ㆍ공급계약체결,2007,3,13,1
348130,002380,Y,케이씨씨,케이씨씨,2007-02-23,20061219800062,None,유,None,정기주주총회결과,2007,2,23,4
348271,007610,Y,선도전기,선도전기,2007-02-16,20061220800013,None,유,None,주주총회소집결의,2007,2,16,4
348480,006740,Y,영풍제지,영풍제지,2007-01-02,20061221800014,None,유,B_23,금전대여결정(자율공시),2007,1,2,1
348957,000270,Y,기아자동차,기아자동차,2007-01-02,20061226800078,None,유,E_4,영업실적등에대한전망(공정공시),2007,1,2,1
348959,000270,Y,기아자동차,기아자동차,2007-01-02,20061226800084,None,유,E_4,영업(잠정)실적(공정공시),2007,1,2,1
348963,015540,Y,메디플란트,메디플란트,2007-01-04,20061226800128,None,유,None,기타안내사항(안내공시),2007,1,4,3
348972,000640,Y,동아쏘시오홀딩스,동아쏘시오홀딩스,2007-01-02,20061226800192,None,유,E_4,영업실적등에대한전망(공정공시),2007,1,2,1
349151,017800,Y,현대엘리베이터,현대엘리베이터,2007-01-03,20061227800049,None,유,E_4,영업실적등에대한전망(공정공시),2007,1,3,2
349153,002360,Y,SH에너지화학,SH에너지화학,2007-01-03,20061227800057,None,유,G_01,최대주주등소유주식변동신고서,2007,1,3,2
349156,004200,Y,고려개발,고려개발,2007-01-02,20061227800063,None,유,G_01,최대주주등소유주식변동신고서,2007,1,2,1
349157,034220,Y,LG디스플레이,LG디스플레이,2007-01-05,20061227800065,None,유,None,기업설명회(IR)개최(안내공시),2007,1,5,4
349173,006120,Y,SK디스커버리,SK디스커버리,2007-01-03,20061227800152,None,유,G_01,최대주주등소유주식변동신고서,2007,1,3,2
349181,003960,Y,사조대림,사조대림,2007-01-11,20061227800207,None,유,None,대표이사(대표집행임원)변경(안내공시),2007,1,11,3
349395,002140,Y,고려산업,고려산업,2007-01-02,20061228800035,None,유,G_01,최대주주등소유주식변동신고서,2007,1,2,1
349397,001550,Y,조비,조비,2007-01-02,20061228800040,None,유,G_01,최대주주등소유주식변동신고서,2007,1,2,1
349398,086280,Y,현대글로비스,현대글로비스,2007-01-03,20061228800044,None,유,None,기타안내사항(안내공시),2007,1,3,2
349405,016880,Y,웅진,웅진,2007-01-03,20061228800072,None,유,E_4,영업실적등에대한전망(공정공시),2007,1,3,2
349406,016580,Y,환인제약,환인제약,2007-01-16,20061228800080,None,유,G_02,최대주주등소유주식변동신고서(최대주주변경시),2007,1,16,1
349408,004200,Y,고려개발,고려개발,2007-01-17,20061228800082,None,유정,B_22,[첨부추가]매출액또는손익구조30%(대규모법인은15%)이상변경,2007,1,17,2
349412,033780,Y,케이티앤지,케이티앤지,2007-01-24,20061228800094,None,유,E_4,영업(잠정)실적(공정공시),2007,1,24,2
349413,004200,Y,고려개발,고려개발,2007-01-12,20061228800100,None,유,E_4,결산실적공시예고(안내공시),2007,1,12,4
349416,000430,Y,대원강업,대원강업,2007-02-26,20061228800112,None,유,None,주주총회소집결의,2007,2,26,0
349419,033780,Y,케이티앤지,케이티앤지,2007-01-19,20061228800141,None,유,None,기업설명회(IR)개최(안내공시),2007,1,19,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418195,014790,Y,한라,한라,2007-12-31,20071231800003,None,유,B_9,단일판매ㆍ공급계약체결(자율공시),2007,12,31,0
418199,001020,Y,페이퍼코리아,페이퍼코리아,2007-12-31,20071231800008,None,유,C_03,횡령ㆍ배임혐의발생,2007,12,31,0
418203,003690,Y,코리안리,코리안리,2007-12-31,20071231800017,None,유,E_4,영업(잠정)실적(공정공시),2007,12,31,0
418204,001460,Y,BYC,BYC,2007-12-31,20071231800019,None,유,G_01,최대주주등소유주식변동신고서,2007,12,31,0
418205,001040,Y,CJ,CJ,2007-12-31,20071231800024,None,유,H2_01,지주회사의자회사편입,2007,12,31,0
418207,002240,Y,고려제강,고려제강,2007-12-31,20071231800031,None,유,G_01,최대주주등소유주식변동신고서,2007,12,31,0
418208,025540,Y,한국단자공업,한국단자공업,2007-12-31,20071231800040,None,유,G_01,최대주주등소유주식변동신고서,2007,12,31,0
418209,004990,Y,롯데지주,롯데지주,2007-12-31,20071231800044,None,유,G_01,최대주주등소유주식변동신고서,2007,12,31,0
418211,088790,Y,진도,진도,2007-12-31,20071231800056,None,유정,B_10,[기재정정]유형자산처분결정,2007,12,31,0
418219,019680,Y,대교,대교,2007-12-31,20071231800080,None,유,None,기타안내사항(안내공시),2007,12,31,0
418221,000540,Y,흥국화재,흥국화재,2007-12-31,20071231800097,None,유,E_4,영업(잠정)실적(공정공시),2007,12,31,0
418222,018670,Y,SK가스,SK가스,2007-12-31,20071231800113,None,유,B_7,단일판매ㆍ공급계약체결,2007,12,31,0
418224,015260,Y,에이엔피,에이엔피,2007-12-31,20071231800128,None,유,None,[첨부정정]기타안내사항(안내공시),2007,12,31,0
418225,003060,Y,에이프로젠제약,에이프로젠제약,2007-12-31,20071231800138,None,유,C_03,횡령ㆍ배임혐의발생,2007,12,31,0
418226,003060,Y,에이프로젠제약,에이프로젠제약,2007-12-31,20071231800144,None,유정,ET_01,기타경영사항(자율공시),2007,12,31,0
418230,083650,K,비에이치아이,비에이치아이,2007-12-31,20071231900014,None,코,None,수시공시의무관련사항(공정공시),2007,12,31,0
418231,067160,K,아프리카TV,아프리카TV,2007-12-31,20071231900019,None,코,G_04,대표이사변경,2007,12,31,0
418232,067160,K,아프리카TV,아프리카TV,2007-12-31,20071231900020,None,코,None,주식명의개서정지(주주명부폐쇄),2007,12,31,0
418233,056080,K,유진로봇,유진로봇,2007-12-31,20071231900024,None,코,N_05,조회공시(현저한시황변동관련),2007,12,31,0
418234,042370,K,비츠로테크,비츠로테크,2007-12-31,20071231900028,None,코,N_05,조회공시(현저한시황변동관련),2007,12,31,0
418235,042110,K,에스씨디,에스씨디,2007-12-31,20071231900031,None,코,G_04,대표이사변경,2007,12,31,0
418236,038460,K,바이오스마트,바이오스마트,2007-12-31,20071231900038,None,코,None,신주인수권행사가액의조정,2007,12,31,0
418237,018290,K,지엠피,지엠피,2007-12-31,20071231900040,None,코,N_05,조회공시(현저한시황변동관련),2007,12,31,0
418238,060900,K,퍼시픽바이오,퍼시픽바이오,2007-12-31,20071231900053,None,코,None,신주인수권행사가액의조정,2007,12,31,0
418239,054090,K,삼진엘앤디,삼진엘앤디,2007-12-31,20071231900059,None,코정,B_7,[기재정정]단일판매ㆍ공급계약체결,2007,12,31,0
418240,080010,K,이상네트웍스,이상네트웍스,2007-12-31,20071231900063,None,코,None,임시주주총회결과,2007,12,31,0
418241,041140,K,넥슨지티,넥슨지티,2007-12-31,20071231900066,None,코,B_9,[기재정정]단일판매ㆍ공급계약체결(자율공시),2007,12,31,0
418242,053110,K,소리바다,코스닥시장본부,2007-12-31,20071231900070,None,코,None,추가상장,2007,12,31,0
418243,060900,K,퍼시픽바이오,퍼시픽바이오,2007-12-31,20071231900077,None,코,G_04,대표이사변경,2007,12,31,0
418244,036630,K,세종텔레콤,세종텔레콤,2007-12-31,20071231900084,None,코,None,전환가액의조정,2007,12,31,0

In [93]:
rcp_df[rcp_df['rcp_rt'].isnull()]

,crp_cd,crp_cls,crp_nm,flr_nm,rcp_dt,rcp_no,rcp_rt,rmk,rpt_cat,rpt_nm,rcp_year,rcp_month,rcp_day,rcp_dayofweek
0,023150,Y,MH에탄올,MH에탄올,1999-03-25,19990325000001,None,정,E_1,사업보고서 (1998.12),1999,3,25,3
1,001140,Y,국보,국보,1999-03-25,19990325000003,None,정,E_1,사업보고서 (1998.12),1999,3,25,3
2,014160,Y,대영포장,대영포장,1999-03-25,19990325000008,None,정연,E_1,사업보고서 (1998.12),1999,3,25,3
3,002310,Y,아세아제지,아세아제지,1999-03-25,19990325000015,None,정,E_1,사업보고서 (1998.12),1999,3,25,3
4,015360,Y,예스코,예스코,1999-03-25,19990325000016,None,정,E_1,사업보고서 (1998.12),1999,3,25,3
5,003580,Y,동원,동원,1999-03-26,19990326000007,None,,E_1,사업보고서 (1998.12),1999,3,26,4
6,005030,Y,부산주공,부산주공,1999-03-27,19990327000001,None,,E_1,사업보고서 (1998.12),1999,3,27,5
7,014910,Y,성문전자,성문전자,1999-03-27,19990327000005,None,정,E_1,사업보고서 (1998.12),1999,3,27,5
8,029530,Y,신도리코,신도리코,1999-03-29,19990329000001,None,정,E_1,사업보고서 (1998.12),1999,3,29,0
9,005320,Y,국동,국동,1999-03-29,19990329000003,None,정연,E_1,사업보고서 (1998.12),1999,3,29,0
10,011150,Y,CJ씨푸드,CJ씨푸드,1999-03-29,19990329000007,None,정,E_1,사업보고서 (1998.12),1999,3,29,0
11,017960,Y,한국카본,한국카본,1999-03-29,19990329000013,None,,E_1,사업보고서 (1998.12),1999,3,29,0
12,004980,Y,성신양회,성신양회,1999-03-29,19990329000032,None,정연,E_1,사업보고서 (1998.12),1999,3,29,0
13,015350,Y,부산도시가스,부산도시가스,1999-03-29,19990329000036,None,정,E_1,사업보고서 (1998.12),1999,3,29,0
14,009160,Y,SIMPAC,SIMPAC,1999-03-29,19990329000043,None,,E_1,사업보고서 (1998.12),1999,3,29,0
15,007340,Y,디티알오토모티브,디티알오토모티브,1999-03-29,19990329000044,None,정,E_1,사업보고서 (1998.12),1999,3,29,0
16,011000,Y,진원생명과학,진원생명과학,1999-03-29,19990329000047,None,정,E_1,사업보고서 (1998.12),1999,3,29,0
17,002350,Y,넥센타이어,넥센타이어,1999-03-29,19990329000048,None,,E_1,사업보고서 (1998.12),1999,3,29,0
18,000490,Y,대동공업,대동공업,1999-03-29,19990329000051,None,정연,E_1,사업보고서 (1998.12),1999,3,29,0
19,005430,Y,한국공항,한국공항,1999-03-29,19990329000052,None,정,E_1,사업보고서 (1998.12),1999,3,29,0
20,002410,Y,범양건영,범양건영,1999-03-29,19990329000053,None,정,E_1,사업보고서 (1998.12),1999,3,29,0
21,002920,Y,유성기업,유성기업,1999-03-29,19990329000054,None,,E_1,사업보고서 (1998.12),1999,3,29,0
22,009970,Y,영원무역홀딩스,영원무역홀딩스,1999-03-29,19990329000057,None,정연,E_1,사업보고서 (1998.12),1999,3,29,0
23,000700,Y,유수홀딩스,유수홀딩스,1999-03-29,19990329000059,None,정,E_1,사업보고서 (1998.12),1999,3,29,0
24,005090,Y,삼광글라스,삼광글라스,1999-03-29,19990329000062,None,정연,E_1,사업보고서 (1998.12),1999,3,29,0
25,014530,Y,극동유화,극동유화,1999-03-29,19990329000070,None,정,E_1,사업보고서 (1998.12),1999,3,29,0
26,017390,Y,서울도시가스,서울도시가스,1999-03-29,19990329000073,None,정연,E_1,사업보고서 (1998.12),1999,3,29,0
27,003620,Y,쌍용자동차,쌍용자동차,1999-03-29,19990329000074,None,,E_1,사업보고서 (1998.12),1999,3,29,0
28,006110,Y,삼아알미늄,삼아알미늄,1999-03-29,19990329000075,None,정,E_1,사업보고서 (1998.12),1999,3,29,0
29,007690,Y,국도화학,국도화학,1999-03-29,19990329000076,None,정연,E_1,사업보고서 (1998.12),1999,3,29,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255824,005500,Y,삼진제약,삼진제약,2018-02-12,20180212800221,None,유,None,주주총회소집결의,2018,2,12,0
1255825,009310,Y,참엔지니어링,참엔지니어링,2018-02-12,20180212800252,None,유,S_02,소송등의판결ㆍ결정,2018,2,12,0
1255826,161890,Y,한국콜마,한국콜마,2018-02-12,20180212800262,None,유,G_01,최대주주등소유주식변동신고서,2018,2,12,0
1255827,000890,Y,보해양조,보해양조,2018-02-12,20180212800277,None,유,G_01,최대주주등소유주식변동신고서,2018,2,12,0
1255931,049080,K,기가레인,기가레인,2018-02-12,20180212900070,None,코,B_7,단일판매ㆍ공급계약체결,2018,2,12,0
1255932,259630,K,엠플러스,엠플러스,2018-02-12,20180212900076,None,코,B_7,단일판매ㆍ공급계약체결,2018,2,12,0
1255933,950130,K,엑세스바이오,엑세스바이오,2018-02-12,20180212900082,None,코,None,기업설명회(IR)개최,2018,2,12,0
1255934,065130,K,탑엔지니어링,탑엔지니어링,2018-02-12,20180212900105,None,코,None,매출액또는손익구조30%(대규모법인은15%)이상변동,2018,2,12,0
1255935,219860,K,한화에이스스팩2호,한화에이스스팩2호,2018-02-12,20180212900111,None,코,None,주주총회소집결의,2018,2,12,0
1255936,219860,K,한화에이스스팩2호,한화에이스스팩2호,2018-02-12,20180212900114,None,코,None,매출액또는손익구조30%(대규모법인은15%)이상변동,2018,2,12,0
1255937,279410,K,한화에이스스팩4호,한화에이스스팩4호,2018-02-12,20180212900153,None,코,None,주주총회소집결의,2018,2,12,0
1255938,063440,K,에프엔씨애드컬쳐,에프엔씨애드컬쳐,2018-02-12,20180212900155,None,코,None,매출액또는손익구조30%(대규모법인은15%)이상변동,2018,2,12,0
1255939,267320,K,교보7호스팩,교보7호스팩,2018-02-12,20180212900157,None,코,None,주주총회소집결의,2018,2,12,0
1255940,242040,K,교보비엔케이스팩,교보비엔케이스팩,2018-02-12,20180212900160,None,코,None,주주총회소집결의,2018,2,12,0
1255941,264290,K,한화에이스스팩3호,한화에이스스팩3호,2018-02-12,20180212900183,None,코,None,주주총회소집결의,2018,2,12,0
1255942,148140,K,비디아이,비디아이,2018-02-12,20180212900192,None,코,B_20,"투자판단관련주요경영사항(강릉안인화력 1,2호기 회처리/회정제설비 사전착수지시서 접수)",2018,2,12,0
1255943,089150,K,케이씨티,케이씨티,2018-02-12,20180212900193,None,코,None,매출액또는손익구조30%(대규모법인은15%)이상변동,2018,2,12,0
1255944,085660,K,차바이오텍,차바이오텍,2018-02-12,20180212900197,None,코,ET_01,기타경영사항(특허권취득)(자율공시)(피부줄기세포 배양액을 포함하는 피부 노화 예방 ...,2018,2,12,0
1255945,036640,K,HRS,HRS,2018-02-12,20180212900209,None,코,K_1,현금ㆍ현물배당결정,2018,2,12,0
1255946,095190,K,이엠코리아,이엠코리아,2018-02-12,20180212900214,None,코,B_9,단일판매ㆍ공급계약체결(자율공시),2018,2,12,0
1255947,263860,K,지니언스,지니언스,2018-02-12,20180212900222,None,코,E_4,영업(잠정)실적(공정공시),2018,2,12,0
1255948,263860,K,지니언스,지니언스,2018-02-12,20180212900223,None,코,E_4,연결재무제표기준영업(잠정)실적(공정공시),2018,2,12,0
1255949,257730,K,신한제3호스팩,신한제3호스팩,2018-02-12,20180212900239,None,코,None,매출액또는손익구조30%(대규모법인은15%)이상변동,2018,2,12,0
1255950,012790,K,신일제약,신일제약,2018-02-12,20180212900248,None,코,K_1,현금ㆍ현물배당결정,2018,2,12,0
1255951,045340,K,토탈소프트,토탈소프트,2018-02-12,20180212900249,None,코,None,매출액또는손익구조30%(대규모법인은15%)이상변동,2018,2,12,0
1255952,094360,K,칩스앤미디어,칩스앤미디어,2018-02-12,20180212900250,None,코,None,주주총회소집결의,2018,2,12,0
1255953,255220,K,SG,SG,2018-02-12,20180212900263,None,코,None,매출액또는손익구조30%(대규모법인은15%)이상변동,2018,2,12,0
1255954,080000,K,에스엔유,에스엔유,2018-02-12,20180212900266,None,코,None,매출액또는손익구조30%(대규모법인은15%)이상변동,2018,2,12,0
1255955,050090,K,휘닉스소재,휘닉스소재,2018-02-12,20180212900272,None,코,None,전환사채(해외전환사채포함)발행후만기전사채취득(제6회차),2018,2,12,0
1255956,095190,K,이엠코리아,이엠코리아,2018-02-12,20180212900276,None,코,B_9,단일판매ㆍ공급계약체결(자율공시),2018,2,12,0

In [176]:
# 2016년 7월 31일까지 9:00~15:00 / 2016년 8월 1일부터 9:00~15:30
rcp_df.groupby(['rcp_no', 'rcp_hour']).count()

,,crp_cd,crp_cls,crp_nm,flr_nm,rcp_dt,rcp_rt,rmk,rpt_cat,rpt_nm,rcp_year,rcp_month,rcp_day,rcp_dayofweek
rcp_no,rcp_hour,,,,,,,,,,,,,
19990325000001,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990325000003,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990325000008,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990325000015,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990325000016,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990326000007,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990327000001,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990327000005,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000001,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000003,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000007,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000013,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000032,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000036,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000043,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000044,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000047,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000048,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000051,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000052,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000053,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000054,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000057,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000059,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000062,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000070,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000073,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000074,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000075,0,1,1,1,1,1,0,1,1,1,1,1,1,1
19990329000076,0,1,1,1,1,1,0,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20180802000021,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802000025,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802000027,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802000029,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802000033,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802000035,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802000040,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802000041,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802000043,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802000045,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802000047,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802000050,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802000060,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802000067,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802000068,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802000069,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802000073,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802000074,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802000078,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802800107,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802800111,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802800123,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802900003,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802900054,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802900088,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802900089,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802900119,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802900120,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802900122,0,1,1,1,1,1,1,1,0,1,1,1,1,1
20180802900130,0,1,1,1,1,1,1,1,0,1,1,1,1,1

## rcp_df에 datecd 만들기

In [215]:
rcp_df['rcp_year'] = rcp_df['rcp_year'].astype(str)
rcp_df['rcp_month'] = rcp_df['rcp_month'].astype(str)
rcp_df['rcp_day'] = rcp_df['rcp_day'].astype(str)
rcp_df['crp_cd'] = rcp_df['crp_cd'].astype(str)

In [216]:
rcp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1297983 entries, 0 to 1297982
Data columns (total 14 columns):
crp_cd           1297983 non-null object
crp_cls          1297983 non-null object
crp_nm           1297983 non-null object
flr_nm           1297983 non-null object
rcp_dt           1297983 non-null datetime64[ns]
rcp_no           1297983 non-null object
rcp_rt           42272 non-null object
rmk              1297983 non-null object
rpt_cat          808899 non-null object
rpt_nm           1297983 non-null object
rcp_year         1297983 non-null object
rcp_month        1297983 non-null object
rcp_day          1297983 non-null object
rcp_dayofweek    1297983 non-null int64
dtypes: datetime64[ns](1), int64(1), object(12)
memory usage: 138.6+ MB

In [221]:
rcp_df['rcp_month'] = rcp_df['rcp_month'].str.zfill(2)
rcp_df['rcp_day'] = rcp_df['rcp_day'].str.zfill(2)

In [223]:
rcp_df['datecd'] = rcp_df.loc[:,'rcp_year'] + rcp_df.loc[:,'rcp_month']\
+ rcp_df.loc[:,'rcp_day'] + rcp_df.loc[:,'crp_cd']

In [91]:
print(rcp_df.iloc[1255956])
print(rcp_df.iloc[1255957]) #1255957 부터 시간 있음 2018-02-12 13:43

crp_cd                        095190
crp_cls                            K
crp_nm                         이엠코리아
flr_nm                         이엠코리아
rcp_dt           2018-02-12 00:00:00
rcp_no                20180212900276
rcp_rt                          None
rmk                                코
rpt_cat                          B_9
rpt_nm             단일판매ㆍ공급계약체결(자율공시)
rcp_year                        2018
rcp_month                          2
rcp_day                           12
rcp_dayofweek                      0
Name: 1255956, dtype: object
crp_cd                        086670
crp_cls                            K
crp_nm                           비엠티
flr_nm                           비엠티
rcp_dt           2018-02-12 00:00:00
rcp_no                20180212900282
rcp_rt                         13:43
rmk                                코
rpt_cat                          E_4
rpt_nm                영업(잠정)실적(공정공시)
rcp_year                        2018
rcp_month                          2
rcp_day                           12
rcp_dayofweek                      0
Name: 1255957, dtype: object

## stock_df 와 join (key = datecd)

In [230]:
rcp_df.tail()

,crp_cd,crp_cls,crp_nm,flr_nm,rcp_dt,rcp_no,rcp_rt,rmk,rpt_cat,rpt_nm,rcp_year,rcp_month,rcp_day,rcp_dayofweek,datecd
1297978,080420,K,모다이노칩,모다이노칩,2018-08-02,20180802900089,10:05,코,None,연결재무제표기준영업(잠정)실적(공정공시),2018,08,02,3,20180802080420
1297979,072770,K,네오디안테크놀로지,네오디안테크놀로지,2018-08-02,20180802900119,10:45,코,None,주주총회소집결의,2018,08,02,3,20180802072770
1297980,080160,K,모두투어,모두투어,2018-08-02,20180802900120,10:44,코,None,기업설명회(IR)개최,2018,08,02,3,20180802080160
1297981,072770,K,네오디안테크놀로지,네오디안테크놀로지,2018-08-02,20180802900122,10:48,코,None,주식명의개서정지(주주명부폐쇄),2018,08,02,3,20180802072770
1297982,043590,K,크로바하이텍,크로바하이텍,2018-08-02,20180802900130,11:29,코,None,유상증자1차발행가액결정,2018,08,02,3,20180802043590

In [267]:
# convert from list of dict  to dataframe
stock_df = pd.DataFrame.from_dict(stock_table)

In [268]:
len(stock_table)

6818450

In [270]:
stock_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6818450 entries, 0 to 6818449
Data columns (total 9 columns):
close     float64
crp_cd    object
date      object
datecd    object
diff      float64
high      float64
low       float64
open      float64
volume    float64
dtypes: float64(6), object(3)
memory usage: 468.2+ MB

In [240]:
stock_df['diff'] = stock_df['diff'].astype(int)
stock_df['high'] = stock_df['high'].astype(int)
stock_df['low'] = stock_df['low'].astype(int)
stock_df['open'] = stock_df['open'].astype(int)
stock_df['volume'] = stock_df['volume'].astype(int)

In [243]:
stock_df.head()

ValueError: Unknown format code 'd' for object of type 'float'

ValueError: Unknown format code 'd' for object of type 'float'

In [242]:
stock_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6818450 entries, 0 to 6818449
Data columns (total 9 columns):
close     float64
crp_cd    object
date      object
datecd    object
diff      int64
high      int64
low       int64
open      int64
volume    int64
dtypes: float64(1), int64(5), object(3)
memory usage: 468.2+ MB

In [237]:
join_df = rcp_df.merge(stock_df, on = 'datecd', how = 'left') #join과 merge의 차이점?

In [238]:
join_df.head()

ValueError: Unknown format code 'd' for object of type 'float'

ValueError: Unknown format code 'd' for object of type 'float'

## 당일종가 - 당일시가

## 당일종가 - 전일종가